### ISSUE TITLE
Azure KeyVault / Overall Service Api Latency

### ISSUE THREAD

**Issue by heoelri** [Azure/ahm-templates#9]
The "Overall Service Api Latency" metric went to unhealthy today. 

<img width="422" alt="image" src="https://user-images.githubusercontent.com/17407022/220853013-22a687dc-b355-4efa-93ea-35d4afe624d7.png">

Our current recommendations is: 

https://github.com/Azure/ahm-templates/blob/310cfe65156daafbfbb59c2513ab746e41e05be7/templates/microsoft.keyvault/vaults/metrics.json#L24-L33

Any thoughts? Do we need to increase the thresholds for degraded and unhealthy? For example to degraded >= 25ms and unhealthy >= 50ms for now?

**Comment by msimecek** [comment]
I think unhealthy should be something way higher - 200+.

**Comment by heoelri** [comment]
<img width="425" alt="image" src="https://user-images.githubusercontent.com/17407022/220934724-05d5d428-9b7c-4d44-88fe-dc5d984ec03a.png">
